# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |v|
    v.cpus = 6
    v.memory = 16384
  end
  config.vm.provision :shell, path: "bootstrap.sh"

  # The Tomcat port
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # The eXist-db port
  # The username is admin, no password
  # TODO default a password
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  # The Solr port
  config.vm.network "forwarded_port", guest: 8983, host: 8983
end
